reset_error:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: locking_cover

force_relax:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: locking_cover
